version: '2'
services:
  mongodb:
    image: mongo:5.0.13
    container_name: graylog_mongo
    volumes:
      - graylog_mongo_data:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: graylog_elasticsearch
    volumes:
      - graylog_es_data:/usr/share/elasticsearch/data 
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - node.max_local_storage_nodes=4
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  graylog:
    image: graylog/graylog:5.0
    container_name: graylog
    volumes:
      - graylog_data:/usr/share/graylog/data
    env_file:
      - .env.graylog
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - 7555:7555
      - 8514:8514
      - 8514:8514/udp
      - 12201:12201
      - 12201:12201/udp
volumes:
  graylog_mongo_data:
    driver: local
  graylog_es_data:
    driver: local
  graylog_data:
    driver: local